Fix misspelling errors
qgis/QGIS-Documentation pull request #6134
Opened 2020-09-27 12:53 UTC by ka1bi4

Fix some misspelling errors.

2020-09-27 12:54 UTC, ka1bi4 commented
Hi,
I fixed some misspelling errors.

2020-09-27 16:33 UTC, havatv requested changes
Thanks @ka1bi4 .
This looks good, but there are  a few things that have to be fixed before we can merge. See my suggestions and comments.

2020-09-27 16:33 UTC, havatv commented on docs/training_manual/basic_map/overview.rst
> +Favorite``. You should then be able to see your folder in the |favorites|
```suggestion
Favorite``. You should then be able to see your folder in the |favourites|
```
We can't change this only here. It is a reference (substitution)

2020-09-27 16:33 UTC, havatv commented on docs/training_manual/basic_map/preparation.rst
> +.. _tm_prepare_a_map:
```suggestion
.. _tm_pepare_a_map:
```
This is an anchor, so all references to itmust also be changed

2020-09-27 16:33 UTC, havatv commented on docs/training_manual/processing/john_snow.rst
> +The first thing to do is to calculating the Voronoi diagram (a.k.a. Thyessen polygons) of the pumps layer, to get the influence zone of each pump. The *Voronoi Diagram* algorithm can be used for that
```suggestion
The first thing to do is to calculating the Voronoi diagram (a.k.a. Thiessen polygons) of the pumps layer, to get the influence zone of each pump. The *Voronoi Diagram* algorithm can be used for that.
```

2020-09-27 18:46 UTC, DelazJ commented on docs/training_manual/basic_map/preparation.rst
> +.. _tm_prepare_a_map:
better fix the spelling. Done!

2020-09-27 18:46 UTC, DelazJ commented on docs/training_manual/processing/john_snow.rst
> +The first thing to do is to calculating the Voronoi diagram (a.k.a. Thyessen polygons) of the pumps layer, to get the influence zone of each pump. The *Voronoi Diagram* algorithm can be used for that
should this not be calculate?

2020-09-27 19:54 UTC, havatv commented on docs/training_manual/processing/john_snow.rst
> +The first thing to do is to calculate the Voronoi diagram (a.k.a. Thiessen polygons) of the pumps layer, to get the influence zone of each pump. The *Voronoi Diagram* algorithm can be used for that.
```suggestion
The first thing to do is to calculate the Voronoi diagram (a.k.a. Thiessen
polygons) of the pumps layer, to get the influence zone of each pump.
The *Voronoi Diagram* algorithm can be used for that.
```
Too long line...

2020-09-27 20:59 UTC, ka1bi4 commented on docs/training_manual/basic_map/overview.rst
> +Favorite``. You should then be able to see your folder in the |favorites|
Ok, just notice you about this moment.

2020-09-27 21:55 UTC, havatv commented on docs/training_manual/basic_map/overview.rst
> +Favorite``. You should then be able to see your folder in the |favorites|
@ka1bi4, I suggest we undo this change and merge. You can fix the substitution in a later PR.

2020-09-28 06:30 UTC, ka1bi4 commented on docs/training_manual/processing/john_snow.rst
> +The first thing to do is to calculate the Voronoi diagram (a.k.a. Thiessen polygons) of the pumps layer, to get the influence zone of each pump. The *Voronoi Diagram* algorithm can be used for that.
Hm, maybe:
 To get the influence zone of each pump, calculate the the Voronoi diagram (a.k.a. Thiessen
polygons). The *Voronoi Diagram* algorithm can be used for that.

2020-10-07 07:29 UTC, ka1bi4 commented
Hi @Delaz and @havatv,
what changes still need to be made to perform the merge?

2020-10-07 12:22 UTC, merged

2020-10-07 12:23 UTC, DelazJ commented
Thanks @ka1bi4  and sorry for the late merge

2020-10-07 21:19 UTC, ka1bi4 commented
@DelazJ, thanks. 
I thought I was missing something to close it 😊