[GPR] Describe 3D and Simplification properties of mesh layer
qgis/QGIS-Documentation pull request #6844
Opened 2021-07-31 04:56 UTC by DelazJ

Should fix #4941 fix #4806 fix #4937 fix #4998
Again some features I couldn't understand their function

2021-08-16 06:11 UTC, PeterPetrik commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +  * :guilabel:`Smooth triangles`: ???
@vcloarec what are smooth triangles?

2021-08-16 06:11 UTC, PeterPetrik commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +  * :guilabel:`Level of detail`: ???
in the layer properties -> rendering -> simplify mesh you can create something like raster overviews for mesh. So when you zoom out, some triangles are simplified and "merged" to bigger chunks. this helps a lot for 2d/3d rendering. Here you can choose which "level of detail" you want to use from the set.

2021-08-25 16:56 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +  * :guilabel:`Smooth triangles`: ???
visual effect that smooths the angles between triangles.

Not smoothed:
![image](https://user-images.githubusercontent.com/7416892/130832892-05066109-c7d0-49ae-b5d1-8f096bf31cd0.png)

Smoothed:
![image](https://user-images.githubusercontent.com/7416892/130833052-aed9fde0-d5bd-4fc7-9a99-de71473e9f6c.png)

2021-12-05 15:55 UTC, DelazJ commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +  * :guilabel:`Level of detail`: ???
opened a report for this at https://github.com/qgis/QGIS/issues/44868

2022-01-09 00:39 UTC, vcloarec requested changes

2022-01-09 00:39 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +    with less details.
Add:
    This option is only available if 'Simplify mesh' option is activated.

2022-01-09 00:39 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +* :guilabel:`Vertical settings` to control what to display
```suggestion
* :guilabel:`Vertical settings` to control behavior of the vertical component of vertices of rendered triangles
```

2022-01-09 00:39 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +    the vertices Z value
```suggestion
    the vertices native Z value
```

2022-01-09 00:39 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +As mesh layers can have millions of triangles, their rendering can sometimes
```suggestion
As mesh layers can have millions of faces, their rendering can sometimes
```

2022-01-09 00:39 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +be very slow, especially when all the triangles are displayed in the view
```suggestion
be very slow, especially when all the faces are displayed in the view
```

2022-01-09 00:39 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +and select at which level of detail you would like QGIS to render the mesh layer.
```suggestion
and select at which level of detail you would like QGIS to render the mesh layer.
Note that the simplify mesh contains only triangular faces.
```

2022-01-09 00:39 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +   Hope that I caught the idea.
yes, you are right, this is confusing. The label is wrong, this should be "Minimum mesh resolution". 

And in hindsight, I am wondering if we set the label with "Minimum triangle size" instead will not be clearer. In this case, we need to change also the suffix in the gui from "pixels/triangle" to "pixels"

2022-01-09 11:03 UTC, DelazJ commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +    with less details.
```suggestion
    with less details.
    This option is only available if the :guilabel:`Simplify mesh` option under
    the :guilabel:`Rendering` tab is activated.
```

2022-01-09 11:04 UTC, DelazJ commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +   Hope that I caught the idea.
```suggestion
* :guilabel:`Minimum triangle size`: the average size (in pixels)
  of the triangles that is permitted to display. If the average size of the
  mesh is lesser than this value, the rendering of a lower level of details
  mesh is triggered.

```

2022-01-10 06:40 UTC, merged

2022-01-10 06:42 UTC, DelazJ commented
Thanks a lot @PeterPetrik and @vcloarec for the reviews.