Introducing mesh algorithms
qgis/QGIS-Documentation pull request #7039
Opened 2021-11-06 07:52 UTC by DelazJ

This is an initial walk through the mesh algorithms. I'm not a user of this type of data and probably lack some knowledge so there are some blank cells in the description
Let's say that it fixes #4341 (and more unreported)

2022-01-09 01:48 UTC, vcloarec requested changes

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - Interval between generated levels.
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - Starting level values of contours.
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - Maximum values of contours, that is no generated levels will be greater that this value.
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - List of wanted levels of contours (separated by commas). If filled, the increment, minimum, and maximum field will not be considered.
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +Creates a TIN mesh layer from vector layers.
```suggestion
Creates a TIN mesh layer from vector layers. The TIN mesh is created using a Delaunay triangulation.
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - If checked, the Z value of vector layer points or polygons/lines vertices will be used to assign the Z value of the vertex mesh layer. Only available if the input layers are 3D.
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - Lines where the data will be extracted from the dataset mesh
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - The distance between points on the lines where the data will be extracted from the dataset mesh.
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - Coordinate type of vector value exportation: cartesian, polar or both.
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - Vector layer containing points where the data will be extracted from the dataset mesh
```

2022-01-09 01:48 UTC, vcloarec commented on docs/user_manual/processing_algs/qgis/mesh.rst
> +     -
```suggestion
     - Pixel size of the output raster layer.
```

2022-02-03 14:20 UTC, vcloarec approved these changes

2022-02-04 10:36 UTC, DelazJ commented
Thanks @vcloarec

2022-02-04 11:17 UTC, merged