Explain how Z values are asssigned to mesh elements
qgis/QGIS-Documentation pull request #7730
Opened 2022-08-22 22:15 UTC by DelazJ

refs #6883, refs qgis/QGIS#45140
Completes #7729

2022-09-30 02:01 UTC, vcloarec requested changes

2022-09-30 02:01 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> + | Vertex on an edge shared by two faces | ---                     | Mesh layer                    | Interpolated from the faces' vertices    |
```suggestion
 | Vertex on an edge shared by two faces | ---                     | Mesh layer                    | Interpolated from the edge' vertices    |
```

2022-10-03 02:10 UTC, DelazJ reviewed
Thanks @vcloarec 
Few questions below and also, is the table understandable or do you think of any better formatting?

2022-10-03 02:10 UTC, DelazJ commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> + | Vertex on an edge shared by two faces | ---                     | Mesh layer                    | Interpolated from the faces' vertices    |
Any reason to have removed the "vertex on unshared edge" rows?

2022-10-03 02:10 UTC, DelazJ commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> + | Vertex snapped to a 2D vector feature | ---                     | ---                           | No value                                 |
Should it be backported?

2022-10-03 02:22 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> + | Vertex snapped to a 2D vector feature | ---                     | ---                           | No value                                 |
The fix should be backported (I just added the label).
If you ask for the doc, maybe it should be backported once the fix will be effectively backported?

2022-10-03 02:27 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> + | Vertex on an edge shared by two faces | ---                     | Mesh layer                    | Interpolated from the faces' vertices    |
For vertex on edge inserted on an edge, the behavior is the same if the edge is shared or not by faces: the value is interpolated between the two vertices at the extremity of the edge.
So, better to remove also "shared by two faces" in line 711.

2022-10-03 02:43 UTC, DelazJ commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> + | Vertex on an edge shared by two faces | ---                     | Mesh layer                    | Interpolated from the faces' vertices    |
I'm not that sure. See video where numbers represent vertex z value and what happens (new vertex takes value from widget). Peek is bugging here so can't record but if I select vertices before adding the new one, I get the average value assigned.
https://user-images.githubusercontent.com/7983394/193492327-8ff3493a-4e27-4120-836c-59d555bcdde5.mp4

2022-10-03 03:12 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> + | Vertex on an edge shared by two faces | ---                     | Mesh layer                    | Interpolated from the faces' vertices    |
Indeed, may be a bug... I will look at...

2022-10-03 03:29 UTC, DelazJ commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> + | Vertex snapped to a 2D vector feature | ---                     | ---                           | No value                                 |
I was asking for code but your reply made me realize that I didn't backport any editing changes to 3.22 docs. So done now at #7818 (allowing you to review the unreviewed bits I merged last week - I'll forward port your suggestions)

2022-10-17 22:04 UTC, merged