Add tools to reshape mesh geometries
qgis/QGIS-Documentation pull request #7733
Opened 2022-08-22 22:17 UTC by DelazJ

Fixes #6930, refs qgis/QGIS#45186, refs qgis/QGIS#44169
Completes #7729

2022-09-29 21:41 UTC, vcloarec requested changes

2022-09-29 21:41 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +provides advanced ways to split faces of a mesh using a line geometry.
```suggestion
provides advanced ways to apply break lines using lines geometry.
```

2022-09-29 21:41 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +3D contours you may have got by other means.
```suggestion
lines, as river banks or border of road embankments.
```

2022-09-29 21:41 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +This can be used for example to locally modify a mesh layer with a more accurate
```suggestion
This can be used for example to locally modify a mesh layer with accurate
```

2022-09-29 21:41 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +The mesh frame and properties are affected along that line.
```suggestion
A break line will force the mesh to have edges a long the line. Note that the break line will not be considered persistent once the operation done. Resulting edges will not be constraint anymore and could be modified as other edges.
```

2022-09-29 21:41 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +you can set from the |meshEditForceByVectorLines| :sup:`Force by Selected
```suggestion
Mesh faces that overlap the line geometry or the polygon's boundary will be affected in a way that depends on options you can set from the |meshEditForceByVectorLines| :sup:`Force by Selected
```

2022-09-29 21:41 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +  added to the mesh whenever the line intersects an interior edge.
```suggestion
* |checkbox| :guilabel:`Add new vertex on intersecting edges`: with this option, a new vertex is added each time the forcing line intersect an edge. This option leads to split along the line each encountered faces.
Without this option, each encountered faces are removed and replaced by faces coming from a triangulation with only the existing vertices plus the vertices of the forcing lines (new vertices are also added on the boundary edge intersecting the forcing lines).
```

2022-09-29 21:41 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +  vertex to split the face.
```suggestion
  vertex instead.
```

2022-10-03 02:35 UTC, DelazJ commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +The mesh frame and properties are affected along that line.
@vcloarec I do not understand the last sentence. When were the "resulting edges" considered as constraints? They didn't exist few seconds ago, did they?

2022-10-04 01:16 UTC, vcloarec commented on docs/user_manual/working_with_mesh/mesh_properties.rst
> +The mesh frame and properties are affected along that line.
When building TIN DEM (with other tools than QGIS), user can often add a break line. This constraint will not move, and the TIN will always be constrained by the line, concerned edge will not move, whatever the changes around.
Here with QGIS, we can add a constraint by drawing the line, just after drawing the line, the mesh will be constrained by this line, but after this mesh changes, the line is not here anymore and the mesh is not constrained anymore, changes around can lead to change edges that was on line.
That why I didn't call this editing tool "add a break line" but "force by line", and I think it is important to talk about because user can be used with real break lines.

I hope it is more clear.

2022-10-13 08:54 UTC, merged