QGIS server containerized deployment
qgis/QGIS-Documentation pull request #8407
Opened 2023-07-20 18:09 UTC by alexm98

Goal: Fix non-working examples for containerized deployment of QGIS Server.

The current documentation on containerized deployment includes some steps that if followed, will not work. Such as:

- `kubectl apply -k` will expect to have a kustomization.yaml file that is nowhere present in the documentation. The way of applying the deployments in this case would be `kubectl apply -f`.

- I have also added a ConfigMap for the NGINX configuration. In the current version, the nginx.conf file would not be accessible if the deployment is done outside of a local cluster.

2023-08-06 04:36 UTC, DelazJ commented
@benoitdm-oslandia @nicogodet and any other docker-guy, may I ask for a review please? Thanks.

2023-08-14 07:39 UTC, nicogodet commented
@DelazJ I don't have te required skills to review this PR unfortunately

2023-08-18 09:15 UTC, DelazJ commented
thanks for your reply @nicogodet.
Hopefully someone around has these skills...

2023-08-21 09:14 UTC, benoitdm-oslandia commented
@DelazJ can you assign me this issue please?

2023-08-21 09:42 UTC, benoitdm-oslandia requested changes

2023-08-21 09:42 UTC, benoitdm-oslandia commented on docs/server_manual/containerized_deployment.rst
> +  kubectl apply -f ./
`-k` is for a directory, `-f` for a specific file. You should keep the `-k` as  the k8s deployment uses multiple files.

2023-08-21 09:42 UTC, benoitdm-oslandia commented on docs/server_manual/containerized_deployment.rst
> +    namespace: qgis-server
This is not really useful and could be removed as it may needs special permissions to create new namespaces. Also, changing the namespace induces to update the cleanup block (line 546).

2023-08-21 09:42 UTC, benoitdm-oslandia commented on docs/server_manual/containerized_deployment.rst
> +    namespace: qgis-server
Same as above.

2023-08-21 09:42 UTC, benoitdm-oslandia commented on docs/server_manual/containerized_deployment.rst
> +                mountPath: /etc/nginx/conf.d/
hum... I have a doubt on this one :/

2023-08-21 12:24 UTC, benoitdm-oslandia commented on docs/server_manual/containerized_deployment.rst
> +  kubectl apply -f ./
Ok my bad! I have re read the man and your are right!

2023-08-28 03:53 UTC, DelazJ commented
@alexm98 @benoitdm-oslandia what is the status, here? I can see some unresolved comments... Thanks

2023-08-28 07:55 UTC, alexm98 commented on docs/server_manual/containerized_deployment.rst
> +    namespace: qgis-server
I agree with you @benoitdm-oslandia as users do need permisions in Kubernetes to create new namespaces. I do not think that chunking everything into the default namespace is better, but this is something that can easily be done by the user themselves. I will make the changes accordingly soon.

2023-09-05 11:18 UTC, alexm98 commented on docs/server_manual/containerized_deployment.rst
> +                mountPath: /etc/nginx/conf.d/
This is a solution for deploying to a non-local cluster. nginx.conf does not get copied over to the nginx pod. It does work.

2023-09-05 11:18 UTC, alexm98 commented
@benoitdm-oslandia I have made the changes regarding the namespaces. Could you spare some time please and try out the examples so we can resolve this issue?

2023-09-05 12:25 UTC, benoitdm-oslandia approved these changes

2023-09-05 12:27 UTC, benoitdm-oslandia commented
It is ok to me but I do not know how to set the good statuses!

2023-09-05 13:20 UTC, DelazJ commented
Thanks @alexm98 and @benoitdm-oslandia

2023-09-05 13:25 UTC, merged